version: '3.8'
services:
  keycloak-postgresql:
    container_name: keycloak-postgresql
    image: postgres:14.5
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - keycloak-net

  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:21.1
      env_file: .env
      ports:
      - "9090:8080"
      command: start-dev
      networks:
      - keycloak-net

networks:
    keycloak-net:
